version: 2
jobs:
  build:

    steps:
      - wget https://s3.amazonaws.com/circle-downloads/circle-pyenv-python-3.5.1_1.0_amd64.deb
      - sudo dpkg -i circle-pyenv-python-3.5.1_1.0_amd64.deb
      - checkout

      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: install dependencies
          command: |
            python3.5 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt

      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test
